# Generated by Django 5.2.8 on 2025-11-07 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'العلامة التجارية', 'verbose_name_plural': 'العلامات التجارية'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'تصنيف المنتج', 'verbose_name_plural': 'تصنيفات المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'المنتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'تقييم المنتج', 'verbose_name_plural': 'تقييمات المنتجات'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, help_text='الدولة التي تنتمي إليها العلامة التجارية', max_length=100, null=True, verbose_name='بلد المنشأ'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(help_text='أدخل اسم العلامة التجارية مثل: Apple، Samsung، Huawei...', max_length=100, unique=True, verbose_name='اسم العلامة التجارية'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='وصف اختياري يوضح محتوى هذا التصنيف', null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='أدخل اسم التصنيف الرئيسي مثل: هواتف، سماعات، شواحن...', max_length=100, unique=True, verbose_name='اسم التصنيف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='العلامة التجارية للمنتج (اختياري)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.brand', verbose_name='العلامة التجارية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='حدد التصنيف الذي ينتمي إليه المنتج', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='قم برفع صورة المنتج', null=True, upload_to='products/', verbose_name='صورة المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='أدخل السعر بالريال السعودي', max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='عدد القطع المتوفرة من المنتج', verbose_name='المخزون'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, help_text='تعليق المستخدم حول المنتج (اختياري)', null=True, verbose_name='التعليق'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(help_text='المنتج الذي تم تقييمه', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 نجوم'), (2, '2 نجوم'), (3, '3 نجوم'), (4, '4 نجوم'), (5, '5 نجوم')], help_text='أدخل تقييم المنتج من 1 إلى 5 نجوم', verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(help_text='المستخدم الذي قام بكتابة التقييم', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
