# Generated by Django 5.2.8 on 2025-11-07 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at'], 'verbose_name': 'العنوان', 'verbose_name_plural': 'العناوين'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'permissions': [('can_view_customers', 'يمكنه عرض العملاء'), ('can_manage_staff', 'يمكنه إدارة طاقم المتجر')], 'verbose_name': 'المستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المنطقة / الحي'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=255, verbose_name='الشارع / رقم المنزل'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(help_text='المستخدم المرتبط بهذا العنوان', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff_member',
            field=models.BooleanField(default=False, verbose_name='عضو فريق المتجر'),
        ),
    ]
