# Generated by Django 5.2.8 on 2025-11-07 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_options_alter_user_options_and_more'),
        ('orders', '0001_initial'),
        ('store', '0002_alter_brand_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_at'], 'verbose_name': 'سلة التسوق', 'verbose_name_plural': 'سلال التسوق'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'عنصر في السلة', 'verbose_name_plural': 'عناصر السلال'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'الطلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'عنصر في الطلب', 'verbose_name_plural': 'عناصر الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'عملية دفع', 'verbose_name_plural': 'عمليات الدفع'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(help_text='المستخدم الذي يملك هذه السلة', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(help_text='السلة التي يحتويها هذا العنصر', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart', verbose_name='السلة'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(help_text='المنتج الذي تمت إضافته إلى السلة', on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(help_text='العنوان الذي سيتم شحن الطلب إليه', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address', verbose_name='عنوان الشحن'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المعالجة'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='المستخدم الذي قام بالطلب', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='الطلب الذي ينتمي إليه هذا العنصر', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(help_text='المنتج الذي تم طلبه', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(help_text='الطلب المرتبط بهذه العملية المالية', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='الطلب'),
        ),
    ]
